# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 06:14
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number1', blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator])),
                ('zip_code', blog.fields.ZipCodeField(max_length=5, validators=[blog.validators.zipcode_validator, blog.validators.zipcode_validator, blog.validators.zipcode_validator, blog.validators.zipcode_validator, blog.validators.zipcode_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[blog.validators.MinLengthValidator(4)], verbose_name='제목')),
                ('content', models.TextField(help_text='Markdown문법을 써주세요.')),
                ('lnglat', models.CharField(help_text='경도, 위도 포맷으로 입력', max_length=50, validators=[blog.validators.lnglat_validator])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_field', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_set', to='blog.Post'),
        ),
    ]
