# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160712_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
