# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160719_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[None, None], verbose_name='제목'),
        ),
    ]
