# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 07:20
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160728_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number1',
            field=blog.fields.PhoneNumberField(default='01033334445', max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
            preserve_default=False,
        ),
    ]
