# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pockemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_name', models.CharField(max_length=10)),
                ('po_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('where_catching', models.CharField(max_length=50)),
                ('when_catching', models.DateTimeField(blank=True)),
                ('user_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pockemon',
            name='catched_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pockemon.User'),
        ),
    ]
