# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='where_catching',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
