# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pockemon', '0002_auto_20160718_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='when_catching',
        ),
        migrations.RemoveField(
            model_name='user',
            name='where_catching',
        ),
        migrations.AddField(
            model_name='pockemon',
            name='catched_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pockemon',
            name='catched_where',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
