# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pockemon', '0004_auto_20160718_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pockemon',
            name='catched_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
