# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockemon', '0005_auto_20160718_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pockemon',
            name='po_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
    ]
