# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pockemon', '0006_auto_20160718_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pockemon',
            old_name='catched_where',
            new_name='lnglat',
        ),
    ]
