# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pockemon', '0007_auto_20160718_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pockemon',
            name='catched_by',
        ),
        migrations.RemoveField(
            model_name='pockemon',
            name='catched_when',
        ),
        migrations.RemoveField(
            model_name='pockemon',
            name='lnglat',
        ),
        migrations.AddField(
            model_name='capture',
            name='pockemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pockemon.Pockemon'),
        ),
        migrations.AddField(
            model_name='capture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pockemon.Region'),
        ),
        migrations.AddField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pockemon.User'),
        ),
    ]
