# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pockemon', '0008_auto_20160719_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
